### ISSUE TITLE
[Write | LearningMaterialsTasks] Create slice CompleteTask -> TaskWasCompleted

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#211]
**Dependencies (blockers)**
- [ ] Make sure that #213 is done (must be merged before)

**Subtasks**
Command definition:
- [ ] Create command type `CompleteTask` in `modules/shared/commands`
- [ ] Create `CompleteTaskApplicationCommand` class in `modules/shared/commands`

Domain logic:
- [ ] Create function completeTask in `modules/write/learning-materials-tasks/domain`.
- [ ] Return TaskWasCompleted on every CompleteTask just if task is not already completed.

Application logic:
- [ ] Create CommandHandler for CompleteTaskApplicationCommand
- [ ] Execute domain logic for complete task. Event stream name should be in format `LearningMaterialsTasks_${learningMaterialsId}`

Presentation logic:
- [ ] Create ProcessStEventsRestController in `modules/write/learning-materials-tasks/presentation/rest` with endpoint `POST process-st/events/task-checked-unchecked`
- [ ] Execute CompleteTask command on TaskCheckedUnchecked webook event if task status is Completed

NestJS Module:
- [ ] Create LearningMaterialsTasks module and declare all required providers / controllers. Similar as in LearningMaterialsUrlModule.

**Screenshot from MIRO (Event Modeling):**
![image](https://user-images.githubusercontent.com/18637116/131021102-6827e81a-2a37-4346-af4a-6e9018e3c528.png)
