### ISSUE TITLE
[Presentation | REST API] Use OpenAPI specification as contract testing tool

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#225]
**Context**
When we change something in the backend, we want to be sure that REST API still works as previous or any change in REST API contract is intended.
We won't generate swagger docs from TS code, but do it another way around.
So, we incorporate OPEN API specification from YAML file as API documentation and a tool for REST API contract testing.
It's also a perfect match for mocking with MSW for frontend testing:
https://dev.to/epilot/testing-react-with-jest-and-openapi-mocks-8gc

**Subtasks**
- [ ] Use supertest to make API Calls as described here: https://docs.nestjs.com/fundamentals/testing
- [ ] This test wouldn't be e2e. Mock commandBus in controllers.
- [ ] Test should check controller response on given CommandBus.execute result.
- [ ] Wrtie sample tests for rest api, which validate Open API contract. 

**Helpful resources**:
- Tests similar to that are expected (here project with Express.js):
https://github.com/nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments/blob/develop/backend/test/modules/doubles-tournament/presentation/rest-api/DoublesTournamentRestApiModule.spec.ts
