### ISSUE TITLE
[Write | LearningMaterialsTasks] Create slice UncompleteTask -> TaskWasUncompleted

### ISSUE THREAD

**Issue by MateuszNaKodach** [CodersCrew/coderscamp#230]
**Dependencies (blockers)**
- [x] Make sure that #228 is done (must be merged before)
- [x] Make sure that #211 is done (must be merged before) - work in the same module

**Subtasks**
Command definition:
- [x] Create command type `UncompleteTask ` in `modules/shared/commands`
- [x] Create `UncompleteTaskApplicationCommand` class in `modules/shared/commands` 

Domain logic:
- [x] Create function uncompleteTask in `modules/write/learning-materials-tasks/domain`.
- [x] Return TaskWasUncompleted on every UncompleteTask just if task was already completed.
- [x] Extend function completeTask by taking into account TaskWasUncompleted

Application logic:
- [x] Create CommandHandler for UncompleteTaskApplicationCommand
- [x] Execute domain logic for uncomplete task. Event stream name should be in format `LearningMaterialsTasks_${learningMaterialsId}`

Presentation logic:
- [x] Extend ProcessStEventsRestController endpoint `POST process-st/events/task-checked-unchecked` with following behavior: Execute UncompleteTask command on TaskCheckedUnchecked webook event if task status is NotCompleted

**Screenshot from MIRO (Event Modeling):**
![CodersCamp App _ Event Storming - Frame 3 (2)](https://user-images.githubusercontent.com/18637116/131130067-4925c816-fb71-4a30-950b-edf903623565.jpg)

**Comment by nowakprojects** [comment]
@tomaszdworniczak What is the progress of this task?

**Comment by tomaszdworniczak** [comment]
Sorry for the delay, will deliver till tomorrow's end of the day
