### ISSUE TITLE
Incorporate mutation testing in order to improve code quality

### ISSUE THREAD

**Issue by MateuszNaKodach** [CodersCrew/coderscamp#239]
**Goal**
Test your tests with mutation testing.

**Subtasks**
- [ ] Configure Stryker mutator 
- [ ] Add in package.json script to run mutation testing
- [ ] Run mutation testing for PullRequest only if there are changes for api package.
- [ ] Add mutation testing badge for api package 

**Helpful resources**
- https://stryker-mutator.io/
- Example project with Stryker: https://github.com/nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments/tree/develop/backend

**Comment by nowakprojects** [comment]
@KrystianKjjk the same tool is very useful in .NET. 
I'd be good for you to get familiar with that.
