### ISSUE TITLE
[Write | EmailSender] Create slice SendEmailMessage -> EmailMessageWasSent

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#261]
**Dependencies (blockers)**
- No blockers. Ready to go!

**Subtasks**
Command definition:
- [x] Create command type `SendEmailMessage` in `modules/shared/commands`
- [x] Create `SendEmailMessageApplicationCommand` class in `modules/shared/commands`

Domain logic:
- [x] Create function sendEmailMessage in `modules/write/email-sender/domain`.
- [x] Take SendEmailMessage and appEmailAddress as parameters. appEmailAddress will be `from` of EmailMessageWasSent
- [x] Return EmailMessageWasSent on every SendEmailMessage.

Application logic:
- [x] Create env variable like APP_EMAIL_ADDRESS and use it as argument of sendEmailMessage.
- [x] Create CommandHandler for SendEmailMessageApplicationCommand
- [x] Send email using Nodemailer before saving EmailMessageWasSent event (executing domain logic). 
- [x] Execute domain logic for sendEmailMessage task. Event stream name should be in format `EmailMessage_${emailMessageId}`

Infrastructure
- [x] Configure node-mailer library. Try to use port & adapters architecture. Prepare in application layer port (interface) for sender and implement adapter which will invoke node-mailer. 

Testing strategy
- [x] Write tests for your module by invoking command and checking published event. 
- [ ] Test your command handler by executing a command and checking if mail was successfully sent. You can check if method of EmailSender was called or use Mailhog for that (add to docker-compose). Example test with mailhog you can find here: https://github.com/nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments/blob/develop/backend/test/modules/email-sending/core/application/SendEmail.mailhog-spec.ts

**Screenshot from MIRO (Event Modeling):**

![CodersCamp App _ Event Storming - Frame 3 (3)](https://user-images.githubusercontent.com/18637116/131550367-32952012-473b-4114-a5a9-cd4e26c294dd.jpg)
