### ISSUE TITLE
[Automation | WhenUserRegistrationWasStartedThenRequestEmailConfirmation] Implement slice

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#282]
**Blockers**
- [ ] https://github.com/CodersCrew/coderscamp/issues/279 (RequestEmailConfirmationApplicationCommand is needed)

**Subtasks**
- [ ] Implementation should be placed in `/module/automation/when-user-registration-was-started-then-request-email-confirmation`
- [ ] Create event handler for `UserRegistrationWasStarted` and execute command `RequestEmailConfirmation` on every event. In RequestEmailConfirmation pass `user-registration` as `confirmationFor` value.
- [ ] Create module for this Automation.

**Event Modeling**
MIRO link: https://miro.com/app/board/o9J_lQvnN28=/?moveToWidget=3074457363395417975&cot=14
