### ISSUE TITLE
[Automation | WhenEmailConfirmationWasRequestedThenSendEmailMessage] Implement slice

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#283]
**Blockers**
- [ ] https://github.com/CodersCrew/coderscamp/issues/261 (SendEmailMessageApplicationCommand is needed)

**Subtasks**
- [ ] Implementation should be placed in `/module/automation/when-email-confirmation-was-requested-then-send-email-message`
- [ ] Create event handler for `UserRegistrationWasStarted` and execute command `RequestEmailConfirmation` on every event. In RequestEmailConfirmation pass `user-registration` as `confirmationFor` value.
- [ ] Create module for Automation.

**Event Modeling**
MIRO link: https://miro.com/app/board/o9J_lQvnN28=/?moveToWidget=3074457363395418179&cot=14
