### ISSUE TITLE
[UserRegistration] Take into account email confirmation in user registration process

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#318]
**Blockers**
- None!

**Subtasks**
- [x] `registerUser` in `user-registration/domain/registerUser.ts` should now return only UserRegistrationWasStarted. Fix tests.
- [x] Add command CompleteUserRegistration.
- [x] Add new domain function completeUserRegistration.ts, which will return UserRegistrationWasCompleted for started registration.
- [x] Create command handler for CompleteUserRegistration.
- [ ] Create automation slice WhenEmailConfirmationWasApprovedThenCompleteUserRegistration. Execute CompleteUserRegistration when EmailConfirmationWasApproved (confirmationFor must have value `user-registration`).

**Event Modeling**
MIRO: https://miro.com/app/board/o9J_lQvnN28=/?moveToWidget=3074457363395418540&cot=14

Need help how to implement automation? 
Look for this task implementation: https://github.com/CodersCrew/coderscamp/issues/282
