### ISSUE TITLE
Create CURRENT_COURSE_ID env variable

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#325]
**Subtasks**
- [ ] Add in backend variable CURRENT_COURSE_ID with String type.
- [ ] Set default (current) value for `CodersCamp_7`.
- [ ] This env variable is required.
